title: Terminal

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: pretty

dec_terminal_theme:
  show_post_dates_on_posts: true
